the-collab-lab/tcl-76-smart-shopping-list

src/api/index.js
src/views/Layout.jsx

For this PR we:
- imported `useAuth` and the components for the sign in and sign out buttons
closes #1 
Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.

Add conditional sign in and sign out button

---

src/views/Layout.jsx

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._
Marcos and I added functionality to clicking Home, List, and Manage list links in the navbar using NavLink. We added active status feature to enhance UX, so that users can see which page they are actively viewing.
Issue 3: As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
[#3] (https://github.com/the-collab-lab/tcl-76-smart-shopping-list/issues/3)https://github.com/orgs/the-collab-lab/projects/248?pane=issue&itemId=73841780
`enhancement`

added route handling and added activestatus using navlink

---

src/views/Home.jsx
src/views/List.jsx

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._
Sarah and I worked on task #2. We updated _Home.jsx_ and _List.jsx_ to loop over the data and render the names of each shopping list a user is subscribed to, as well as the names of each item. One thing to note is that we haven’t inserted the **path** prop in _Home.jsx_, as we need further information to create the path. Since we don’t have a database created yet, we attempted to navigate to the /list page, except for one error from _firebase.js_, there are no errors caused by our implementation.
2. As a user, I want to read all of my shopping lists and the items in them.
`feature`

Looped data into List.jsx and into Home.jsx

---

PROJECT-BRIEF.md

Updating project brief to show that we skipped office hours last week and are moving the next learning module down per our discussion in this week's sync!
I recommend looking at the "rich diff" in the "files changed" tab to see the actual differences. I fix minor linting issues automatically on save and it got rid of a bunch of unnecessary spaces and `-`s

Update project brief

---

src/api/firebase.js
src/views/Home.jsx
src/views/Layout.jsx

- Changed Home.jsx to display a form for users to add new lists. Lists get saved to local storage, and then users get redirected to the list page.
- In firebase.js added a return to the createList function, in order to pass the list path into the setListPath hook. In Home.jsx setListPath function takes path and saves it to database and local storage.
- Got great practice working with local storage, and working our way back to find where the path was and debugging to then add the return in firebase.js
- Layout.jsx - fixed a duplicate import
- Closes Issue #4 
UI-related tasks:
Data-related tasks:
- Bug fix
- New feature
- Added a return to the createList function in firebase.js in order to pass it into the setListPath hook.
- Fixed a bug from Issue #3 that wasn't merged yet. Removed …

Mp sm create new shopping list

---

src/views/List.jsx

User can now search for items in their shopping list by searching part of the word or list item. The list displayed is an unfiltered list, and it filters once the user begins typing in the input. The user can use the Clear button to clear the input box. 
closes 7
[x] The form includes the following elements List view, above the shopping list
[x] A text field (with semantic <label>!) which narrows down the list as the user types
When there’s text in the field, some kind of button (e.g., an X) to clear the field. When the field is cleared, the list is reset to its unfiltered state.
`feature` `enhancement`
Visit branch and have a list ready, type letters in the input, and matching words should display, and the clear button should clear the input and the unfiltered list should display.

Ar sm add list filter form

---

src/App.jsx
src/api/firebase.js
src/views/ManageList.jsx

Creating a form to allow the user to invite another person to the current shopping list. If the current user is not valid or the input email is not registered, corresponding alert messages will be displayed. Otherwise, the shopping list will be successfully shared.
closes #6 
`feature`
Tested by inviting an existing user with a new list, and the list name appeared in the Firebase storage shared list array.

added invite friend form and connect with shareList func

---

package-lock.json
package.json
src/App.jsx
src/views/List.jsx
src/views/Modal.jsx

This added an alert to the List page, for users without any items. The popup message alerts them to add items to the Manage List page, and includes a button to navigate them there. We installed the Material UI dependency and used their popup model, and we leveraged conditional rendering to determine when the popup model shows up.
Closes #8 
feature
- use npm i to install MUI
- Create a new shopping list, that should be empty
- When redirected to the list page, a popup window should open
- Button on pop up window sends to you manage list
- If list is still empty, pop up window should still display until items are added
- Should be able to click out of pop up window

Installed MUI and display popup modal when shopping list is empty

---

src/App.jsx
src/views/ManageList.jsx

-First we passed in data as props to the `ManageList `component. After that we were able to use the data object to filter and grab items that matched a users input.
-Then we passed in a regex expression into the `.replace` method to check both spacing and characters in the data and users input. We used `toLowerCase()` to check for matching letters regardless of case.
-We filtered through the list to find any matches, and if the filtered list was > 0 users were alerted that the item exists and `addItem` would not execute.
closes #10
-enhancement
-Alert with a pop-up if a similar item exists.
1. Add new item that already exists on your list
2. Alert will pop-up saying item already exists and in firebase `dateCreated` should not update.
3. Test for spaces in between and characters: aPples or …

Added check for similar items using regex.

---

src/api/firebase.js
src/views/List.jsx

- User's lists are now sorted based on how soon it's recommended they purchase an item (how soon each item's `dateNextPurchased` value is).
- Lists are sorted based on Soon(!!!), Kind of Soon(!!), Not Soon(!), Overdue(!!!!), and Inactive statuses. Different exclamation points illustrate urgency and are placeholder icons until we collaborate on more specific design choices.
- From there, lists are sorted alphabetically.
closes 13
**A stretch goal**
If you complete all of the previous acceptance criteria, consider what happens when an item’s dateNextPurchased has passed, but it isn’t yet inactive. Let’s call that item “overdue”.
`enhancement` `feature`
- User's list is one single list sorted alphabetically.
- User's list is sorted by how soon they can expect to purchase an item.
- List is …

Sm ar items in order issue 13

---

src/components/ListItem.jsx

- In `ListItem` created a div to hold item details
- Passed in `dateNextPurchased` and `totalPurchases` from the `item` object
- displayed the details in a list
- created a toggle button to switch between open and closed states
Ideally, we can use this as a base for more stylistic choices coming up.
closes #37 (#21)
`enhancement`
- View list of items on `List` and there should be a `View Purchase Details` button
- Clicking button will open and should display details
- Open Firebase to list info see if `dateLastPurchased`, `dateNextPurchase`, and `totalPurchases` are the same as whats displayed
- Clicking button should toggle between displaying and hiding the div

View item details

---

src/views/List.jsx
src/views/ManageList.jsx

- User can now add an item directly from the list page instead of navigating to the Manage List page.
- When a user clicks "Add Item" button, the user is navigated to the pre-existing Manage List component (`/manage-list` url)
- After a user is taken to the Add Item component and submits a new item, if the item is successfully added, the user is navigated back to `/list`.
closes 20
`enhancement`
- No add item button
- Add Item button 
- Pull from branch: `ar-add-item-to-list-issue-20`
- Sign in and select a list
- Navigate to List page
- Click **Add Item** button
- You will be taken to `/manage-list` (see url change)
- Add an item, click Submit
- If your item was successfully added, you will be taken back to List page. If your item is not successfully added, you will stay on the Manage …

Ar add item to list issue 20

---

src/App.jsx
src/api/firebase.js
src/views/Home.jsx

Users are able to delete an entire list from their collection from the home page by the click of a Delete button. 
The selected list will be deleted from two locations in the database:
- Users Collection:
From the document associated with the user's email, specifically in the sharedLists array.
- Signed in user's Collection:
From the document representing the shopping lists for that user.
I learned that understanding the Firebase data structure would be crucial for completing this ticket. Initially, I could only delete items from the users' shopping lists, but I wasn't able to remove them from the sharedLists array associated with the users. While the UI updated successfully and one part of the database changed, refreshing the page caused all the deleted shopping lists to reappear. This …

Delete a single list from shopping lists

---

src/api/useAuth.jsx
src/views/Layout.css
src/views/Layout.jsx

Moved the navbar to the top of the screen. Added Sign In/Sign Out button to navbar, and added a page refresh when user clicks Sign Out.
closes 19
`enhancement`
- Pull from `ar-navbar-updates-issue-19`
- Click Sign In
- Follow sign in instructions
- Sign Out

Ar navbar updates issue 19

---

src/App.jsx
src/components/SingleList.jsx

A user has the ability to choose a list from the homepage and be navigated to that list. The user can navigate to another page and the list will stay updated until they decide to choose another list from the homepage.
closes #34 
`enhancement`
1. Go to the homepage
2. Select a list you would like to navigate to by clicking on one
3. Once you are navigated to that list, navigate to another tab (ex: go add a item or go back to home page)
4. Click on List in the navigation bar to see that the list you selected is updated on the list page

Mp navigate to list from homepage

---

package-lock.json
package.json
src/App.jsx
src/components/ShareListComponent.jsx
src/components/index.js
src/views/Home.jsx
src/views/List.jsx
src/views/ManageList.jsx
src/views/ShareList.jsx
src/views/index.js

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._
- Removed share list option from adding item functionality
- Moved share list feature to home page to create a more intuitive user experience
- Changed `Delete` wording to delete icon
- Changed `Share list` wording to share icon
- Changed `Start Voice Input` to microphone icon
closes #45 
`enhancement`
`feature update`
02b4210c2ba">
- Pull from `ar-add-item-updates-issue-25`
- Click the Share Icon
- Share that attributed list with an email address
- Go back to Home
- Navigate to a list
- Click Add Item
- Add item

Ar add item updates issue 25

---

package-lock.json
package.json
src/App.jsx
src/api/useAuth.jsx
src/components/ListItem.jsx
src/index.css
src/views/Layout.jsx
src/views/List.jsx

The main changes made were to the List page with more styles, and incorporates updates to our navbar to help make timely changes.
- Updated the navbar in `Layout.jsx` and List Page on `List.jsx` and` ListItem.jsx`
- Added the User's list name as the header
- Added new global stylings in `index.css`
- Added proper heading elements 
- Incorporated new colors and added responsiveness for the navbar for better user experience
- New icons throughout the List Page
- Removed `ManageList` from the navbar
- Included more spacing between elements
- Added `aria-label`s on elements with icons to provide better descriptions for screen-readers
closes #46 (Issue #26)
`enhancement`
- Pull from `sm-simple-list-view-style-26` branch
- Open the List page from the Navbar
- See items and new stylings on List …

Sm simple list view style 26

---

src/views/Home.jsx

Use Tailwind CSS to create a scrollable card that contains all shopping lists. Each shopping list should have the name aligned to the left, with the delete button and share button aligned to the right. At the bottom, the text input, voice icon, and submit button are properly aligned. On smaller phone screens, these elements should stack vertically.
closes #44 
Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.
`enhancement`
1. Go to the home page and create enough shopping lists to overflow the card.
2. Scroll through the card to view the hidden shopping lists.
3. The "Create a new list" option should remain visible on the homepage.
4. Go to Inspect, and click on the tab icon to check if the …

Style home page and make it responsive

---

src/api/firebase.js
src/views/Home.jsx

This PR resolves a bug where, when a list owner deletes a list, it would be removed from all instances, including for users it was shared with. For users who have the list shared with them, they can only unfollow the list—removing it from their sharedWithMe array—but not delete the original list. I also changed the delete icon to a remove icon for shared lists.
closes #60 
`bug fix` `enhancement` 
1. go to `eb-deletion-issue-32`branch.
2. Share some lists with other users and check the updates in Firebase under the 'sharedWithMe' lists.
3. Delete the list shared with other users and confirm that it is removed from the 'sharedWithMe' lists.

Delete from all instances as lists' owner and unfollow shared lists

---

src/views/Home.jsx
src/views/Layout.css
src/views/Layout.jsx

Add a footer to include developers and mentors' links.
closes #61 
Use one or more labels to help your team understand the nature of the change(s) you’re proposing. E.g., `bug fix` or `enhancement` are common ones.
`enhancement` 
1. go to  `eb-add-footer`
2. Check on different pages to test if the footer stays on the bottom
3. All links should work properly

created footer
